# Generated by Django 2.1.1 on 2018-09-27 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rooms_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rooms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
