# Generated by Django 2.1.1 on 2018-09-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180927_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='text',
            new_name='message',
        ),
    ]
